fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt": "https://github.com/puppetlabs/puppetlabs-apt.git"
    "systemd": "https://github.com/voxpupuli/puppet-systemd.git"
    "zypprepo": "https://github.com/voxpupuli/puppet-zypprepo.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
