#This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'

# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError
end

def with_debian_facts
  let :facts do
    {
      :lsbdistid       => 'Debian',
      :lsbdistcodename => 'jessie',
      :operatingsystem => 'Debian',
      :operatingsystemmajrelease => 8,
      :osfamily        => 'Debian',
      :root_home       => '/root',
    }
  end
end

def with_centos_facts
  let :facts do
    {
      :architecture           => 'x86_64',
      :operatingsystem        => 'CentOS',
      :operatingsystemrelease => '7.0',
      :osfamily               => 'RedHat',
      :root_home              => '/root',
    }
  end
end

def with_redhat_facts
  let :facts do
    {
      :architecture           => 'x86_64',
      :operatingsystem        => 'RedHat',
      :operatingsystemrelease => '7.0',
      :osfamily               => 'RedHat',
      :root_home              => '/root',
    }
  end
end
